version: '3'

services:
  work:
    build:
      context: "."
      dockerfile: Dockerfile
    working_dir: "/workspace"
    command: [ "sleep", "infinity" ]
    volumes:
      - "../:/workspace/:delegated"
    environment:
      - SPANNER_EMULATOR_HOST=spanner:9010

  # to test implementation for postgres
  postgres:
    image: postgres:17.2-alpine3.20
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - "55432:5432"
